export const BASE_URL = "http://localhost:8080/api"
export const ELEVE_BASE_URL = BASE_URL + "/eleve"
export const TUTEUR_BASE_URL = BASE_URL + "/tuteur"
export const YEAR_BASE_URL = BASE_URL + "/schoolYear"
export const NATIONALITIES = [
    {id: 'ma', label: 'Marocaine'},
    {id: 'fr', label: 'Française'},
    {id: 'ch', label: 'Suisse'},
    {id: 'be', label: 'Belge'},
    {id: 'de', label: 'Allemande'},
    {id: 'it', label: 'Italienne'},
    {id: 'af', label: 'Afghane'},
    {id: 'al', label: 'Albanaise'},
    {id: 'dz', label: 'Algerienne'},
    {id: 'us', label: 'Americaine'},
    {id: 'ad', label: 'Andorrane'},
    {id: 'ao', label: 'Angolaise'},
    {id: 'ag', label: 'Antiguaise et barbudienne'},
    {id: 'ar', label: 'Argentine'},
    {id: 'am', label: 'Armenienne'},
    {id: 'au', label: 'Australienne'},
    {id: 'at', label: 'Autrichienne'},
    {id: 'az', label: 'Azerbaïdjanaise'},
    {id: 'bs', label: 'Bahamienne'},
    {id: 'bh', label: 'Bahreinienne'},
    {id: 'bd', label: 'Bangladaise'},
    {id: 'bb', label: 'Barbadienne'},
    {id: 'bz', label: 'Belizienne'},
    {id: 'bj', label: 'Beninoise'},
    {id: 'bt', label: 'Bhoutanaise'},
    {id: 'by', label: 'Bielorusse'},
    {id: 'mm', label: 'Birmane'},
    {id: 'gw', label: 'Bissau-Guinéenne'},
    {id: 'bo', label: 'Bolivienne'},
    {id: 'ba', label: 'Bosnienne'},
    {id: 'bw', label: 'Botswanaise'},
    {id: 'br', label: 'Bresilienne'},
    {id: 'uk', label: 'Britannique'},
    {id: 'bn', label: 'Bruneienne'},
    {id: 'bg', label: 'Bulgare'},
    {id: 'bf', label: 'Burkinabe'},
    {id: 'bi', label: 'Burundaise'},
    {id: 'kh', label: 'Cambodgienne'},
    {id: 'cm', label: 'Camerounaise'},
    {id: 'ca', label: 'Canadienne'},
    {id: 'cv', label: 'Cap-verdienne'},
    {id: 'cf', label: 'Centrafricaine'},
    {id: 'cl', label: 'Chilienne'},
    {id: 'cn', label: 'Chinoise'},
    {id: 'cy', label: 'Chypriote'},
    {id: 'co', label: 'Colombienne'},
    {id: 'km', label: 'Comorienne'},
    {id: 'cg', label: 'Congolaise'},
    {id: 'cr', label: 'Costaricaine'},
    {id: 'hr', label: 'Croate'},
    {id: 'cu', label: 'Cubaine'},
    {id: 'dk', label: 'Danoise'},
    {id: 'dj', label: 'Djiboutienne'},
    {id: 'do', label: 'Dominicaine'},
    {id: 'dm', label: 'Dominiquaise'},
    {id: 'eg', label: 'Egyptienne'},
    {id: 'ae', label: 'Emirienne'},
    {id: 'gq', label: 'Equato-guineenne'},
    {id: 'ec', label: 'Equatorienne'},
    {id: 'er', label: 'Erythreenne'},
    {id: 'es', label: 'Espagnole'},
    {id: 'tl', label: 'Est-timoraise'},
    {id: 'ee', label: 'Estonienne'},
    {id: 'et', label: 'Ethiopienne'},
    {id: 'fj', label: 'Fidjienne'},
    {id: 'fi', label: 'Finlandaise'},
    {id: 'ga', label: 'Gabonaise'},
    {id: 'gm', label: 'Gambienne'},
    {id: 'ge', label: 'Georgienne'},
    {id: 'gh', label: 'Ghaneenne'},
    {id: 'gd', label: 'Grenadienne'},
    {id: 'gt', label: 'Guatemalteque'},
    {id: 'gn', label: 'Guineenne'},
    {id: 'gf', label: 'Guyanienne'},
    {id: 'ht', label: 'Haïtienne'},
    {id: 'gr', label: 'Hellenique'},
    {id: 'hn', label: 'Hondurienne'},
    {id: 'hu', label: 'Hongroise'},
    {id: 'in', label: 'Indienne'},
    {id: 'id', label: 'Indonesienne'},
    {id: 'iq', label: 'Irakienne'},
    {id: 'ie', label: 'Irlandaise'},
    {id: 'is', label: 'Islandaise'},
    {id: 'il', label: 'Israélienne'},
    {id: 'ci', label: 'Ivoirienne'},
    {id: 'jm', label: 'Jamaïcaine'},
    {id: 'jp', label: 'Japonaise'},
    {id: 'jo', label: 'Jordanienne'},
    {id: 'kz', label: 'Kazakhstanaise'},
    {id: 'ke', label: 'Kenyane'},
    {id: 'kg', label: 'Kirghize'},
    {id: 'ki', label: 'Kiribatienne'},
    {id: 'kn', label: 'Kittitienne-et-nevicienne'},
    {id: 'xk', label: 'Kossovienne'},
    {id: 'kw', label: 'Koweitienne'},
    {id: 'la', label: 'Laotienne'},
    {id: 'ls', label: 'Lesothane'},
    {id: 'lv', label: 'Lettone'},
    {id: 'lb', label: 'Libanaise'},
    {id: 'lr', label: 'Liberienne'},
    {id: 'ly', label: 'Libyenne'},
    {id: 'li', label: 'Liechtensteinoise'},
    {id: 'lt', label: 'Lituanienne'},
    {id: 'lu', label: 'Luxembourgeoise'},
    {id: 'mk', label: 'Macedonienne'},
    {id: 'my', label: 'Malaisienne'},
    {id: 'mw', label: 'Malawienne'},
    {id: 'mv', label: 'Maldivienne'},
    {id: 'mg', label: 'Malgache'},
    {id: 'ml', label: 'Malienne'},
    {id: 'mt', label: 'Maltaise'},
    {id: 'mh', label: 'Marshallaise'},
    {id: 'mu', label: 'Mauricienne'},
    {id: 'mr', label: 'Mauritanienne'},
    {id: 'mx', label: 'Mexicaine'},
    {id: 'fm', label: 'Micronesienne'},
    {id: 'md', label: 'Moldave'},
    {id: 'mc', label: 'Monegasque'},
    {id: 'mn', label: 'Mongole'},
    {id: 'me', label: 'Montenegrine'},
    {id: 'mz', label: 'Mozambicaine'},
    {id: 'na', label: 'Namibienne'},
    {id: 'nr', label: 'Nauruane'},
    {id: 'nl', label: 'Neerlandaise'},
    {id: 'nz', label: 'Neo-zelandaise'},
    {id: 'np', label: 'Nepalaise'},
    {id: 'ni', label: 'Nicaraguayenne'},
    {id: 'ng', label: 'Nigeriane'},
    {id: 'ne', label: 'Nigerienne'},
    {id: 'kp', label: 'Nord-coréenne'},
    {id: 'no', label: 'Norvegienne'},
    {id: 'om', label: 'Omanaise'},
    {id: 'ug', label: 'Ougandaise'},
    {id: 'uz', label: 'Ouzbeke'},
    {id: 'pk', label: 'Pakistanaise'},
    {id: 'pw', label: 'Palau'},
    {id: 'ps', label: 'Palestinienne'},
    {id: 'pa', label: 'Panameenne'},
    {id: 'pg', label: 'Papouane-neoguineenne'},
    {id: 'py', label: 'Paraguayenne'},
    {id: 'pe', label: 'Peruvienne'},
    {id: 'ph', label: 'Philippine'},
    {id: 'pl', label: 'Polonaise'},
    {id: 'pr', label: 'Portoricaine'},
    {id: 'pt', label: 'Portugaise'},
    {id: 'qa', label: 'Qatarienne'},
    {id: 'ro', label: 'Roumaine'},
    {id: 'ru', label: 'Russe'},
    {id: 'rw', label: 'Rwandaise'},
    {id: 'lc', label: 'Saint-Lucienne'},
    {id: 'sm', label: 'Saint-Marinaise'},
    {id: 'vc', label: 'Saint-Vincentaise-et-Grenadine'},
    {id: 'sb', label: 'Salomonaise'},
    {id: 'sv', label: 'Salvadorienne'},
    {id: 'ws', label: 'Samoane'},
    {id: 'st', label: 'Santomeenne'},
    {id: 'sa', label: 'Saoudienne'},
    {id: 'sn', label: 'Senegalaise'},
    {id: 'rs', label: 'Serbe'},
    {id: 'sc', label: 'Seychelloise'},
    {id: 'sl', label: 'Sierra-leonaise'},
    {id: 'sg', label: 'Singapourienne'},
    {id: 'sk', label: 'Slovaque'},
    {id: 'si', label: 'Slovene'},
    {id: 'so', label: 'Somalienne'},
    {id: 'sd', label: 'Soudanaise'},
    {id: 'lk', label: 'Sri-lankaise'},
    {id: 'za', label: 'Sud-africaine'},
    {id: 'kr', label: 'Sud-coréenne'},
    {id: 'se', label: 'Suedoise'},
    {id: 'sr', label: 'Surinamaise'},
    {id: 'ze', label: 'Swazie'},
    {id: 'sy', label: 'Syrienne'},
    {id: 'tj', label: 'Tadjike'},
    {id: 'tw', label: 'Taiwanaise'},
    {id: 'tz', label: 'Tanzanienne'},
    {id: 'td', label: 'Tchadienne'},
    {id: 'cz', label: 'Tcheque'},
    {id: 'th', label: 'Thaïlandaise'},
    {id: 'tg', label: 'Togolaise'},
    {id: 'tg', label: 'Tonguienne'},
    {id: 'tt', label: 'Trinidadienne'},
    {id: 'tn', label: 'Tunisienne'},
    {id: 'tm', label: 'Turkmene'},
    {id: 'tr', label: 'Turque'},
    {id: 'tv', label: 'Tuvaluane'},
    {id: 'ua', label: 'Ukrainienne'},
    {id: 'uy', label: 'Uruguayenne'},
    {id: 'vu', label: 'Vanuatuane'},
    {id: 've', label: 'Venezuelienne'},
    {id: 'vn', label: 'Vietnamienne'},
    {id: 'ye', label: 'Yemenite'},
    {id: 'zm', label: 'Zambienne'},
    {id: 'zw', label: 'Zimbabweenne'},
]
export const SECTORS=[
    "Administration, fonction publique",
    "Agroalimentaire",
    "Artisanat d'art",
    "Associations",
    "Banques, assurances, services financiers",
    "Chimie, plastique, conditionnement",
    "Commerce de détail, grande distribution",
    "Communication, marketing, information",
    "Construction, bâtiment, travaux publics",
    "Culture, sports, loisirs",
    "Energie",
    "Enseignement, formation",
    "Environnement, récupération, tri, recyclage, traitement des déchets, matériaux, de l'eau",
    "Equipement, matériel pour activités professionnelles",
    "Fabrication, commerce de gros d'articles destinés à la vente",
    "Gestion, administration des entreprises",
    "Hôtellerie, restauration, tourisme",
    "Immobilier",
    "Industrie textile",
    "Informatique",
    "Ingénieurs d'études et de recherche, chercheurs",
    "Logistique, transports",
    "Matériel électrique, électronique, optique",
    "Mécanique, métallurgie",
    "Minerais, minéraux, sidérurgie",
    "Professions juridiques",
    "Santé, action sociale",
    "Services aux particuliers, collectivités, entreprises",
]